-- Regras do gerador de treino (antes só em BackEndTorv/src/lib/workoutGenerator.js, CATALOG e SLOTS)
-- passam a viver no banco. Espelho das abas Exercicios e Sessoes de BackEndTorv/treino_padrao_referencia.xlsx.
-- Os dados abaixo foram GERADOS por script a partir de CATALOG/SLOTS (não editar à mão): uma tupla por linha.

-- exercises: tipo, nível mínimo e ordem de preferência (catalog_order, a ordem do CATALOG) só no catálogo.
ALTER TABLE "exercises"
  ADD COLUMN "type" VARCHAR(10),
  ADD COLUMN "min_level" VARCHAR(20),
  ADD COLUMN "catalog_order" SMALLINT,
  ADD CONSTRAINT "exercises_type_check" CHECK ("type" IN ('COMPOSTO', 'ISOLADO')),
  ADD CONSTRAINT "exercises_min_level_check" CHECK ("min_level" IN ('INICIANTE', 'INTERMEDIÁRIO', 'AVANÇADO'));
CREATE UNIQUE INDEX "exercises_catalog_order_key" ON "exercises"("catalog_order");

UPDATE "exercises" e SET "type" = v."type", "min_level" = v."min_level", "catalog_order" = v."catalog_order"
FROM (VALUES
  ('supino-reto-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 1),
  ('supino-inclinado-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 2),
  ('supino-reto-com-halteres', 'COMPOSTO', 'INICIANTE', 3),
  ('supino-inclinado-com-halteres', 'COMPOSTO', 'INICIANTE', 4),
  ('chest-press-maquina', 'COMPOSTO', 'INICIANTE', 5),
  ('flexao-de-bracos', 'COMPOSTO', 'INICIANTE', 6),
  ('mergulho-nas-paralelas-foco-peito', 'COMPOSTO', 'INTERMEDIÁRIO', 7),
  ('crossover-na-polia', 'ISOLADO', 'INTERMEDIÁRIO', 8),
  ('crucifixo-com-halteres', 'ISOLADO', 'INTERMEDIÁRIO', 9),
  ('crucifixo-na-maquina-peck-deck', 'ISOLADO', 'INICIANTE', 10),
  ('remada-curvada-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 11),
  ('barra-fixa-pull-up', 'COMPOSTO', 'INTERMEDIÁRIO', 12),
  ('puxada-frontal-na-polia', 'COMPOSTO', 'INICIANTE', 13),
  ('remada-baixa-na-polia-triangulo', 'COMPOSTO', 'INICIANTE', 14),
  ('remada-unilateral-com-haltere-serrote', 'COMPOSTO', 'INICIANTE', 15),
  ('remada-na-maquina', 'COMPOSTO', 'INICIANTE', 16),
  ('barra-fixa-assistida', 'COMPOSTO', 'INICIANTE', 17),
  ('barra-fixa-com-carga', 'COMPOSTO', 'AVANÇADO', 18),
  ('pullover-na-polia-bracos-estendidos', 'ISOLADO', 'INTERMEDIÁRIO', 19),
  ('desenvolvimento-militar-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 20),
  ('desenvolvimento-com-halteres', 'COMPOSTO', 'INICIANTE', 21),
  ('desenvolvimento-na-maquina', 'COMPOSTO', 'INICIANTE', 22),
  ('elevacao-lateral-com-halteres', 'ISOLADO', 'INICIANTE', 23),
  ('crucifixo-inverso-na-maquina-deltoide-posterior', 'ISOLADO', 'INICIANTE', 24),
  ('elevacao-lateral-na-polia', 'ISOLADO', 'INTERMEDIÁRIO', 25),
  ('face-pull', 'ISOLADO', 'INTERMEDIÁRIO', 26),
  ('elevacao-frontal-com-halteres', 'ISOLADO', 'INICIANTE', 27),
  ('rosca-direta-com-barra', 'ISOLADO', 'INICIANTE', 28),
  ('rosca-alternada-com-halteres', 'ISOLADO', 'INICIANTE', 29),
  ('rosca-martelo', 'ISOLADO', 'INICIANTE', 30),
  ('rosca-scott', 'ISOLADO', 'INTERMEDIÁRIO', 31),
  ('rosca-na-polia', 'ISOLADO', 'INTERMEDIÁRIO', 32),
  ('supino-fechado', 'COMPOSTO', 'INTERMEDIÁRIO', 33),
  ('triceps-banco-mergulho-no-banco', 'COMPOSTO', 'INTERMEDIÁRIO', 34),
  ('triceps-pulley-corda-ou-barra', 'ISOLADO', 'INICIANTE', 35),
  ('triceps-testa', 'ISOLADO', 'INTERMEDIÁRIO', 36),
  ('triceps-frances-com-haltere', 'ISOLADO', 'INTERMEDIÁRIO', 37),
  ('agachamento-livre-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 38),
  ('agachamento-frontal', 'COMPOSTO', 'AVANÇADO', 39),
  ('hack-squat', 'COMPOSTO', 'INTERMEDIÁRIO', 40),
  ('agachamento-bulgaro', 'COMPOSTO', 'INTERMEDIÁRIO', 41),
  ('leg-press-45', 'COMPOSTO', 'INICIANTE', 42),
  ('agachamento-goblet', 'COMPOSTO', 'INICIANTE', 43),
  ('agachamento-no-smith', 'COMPOSTO', 'INICIANTE', 44),
  ('afundo-passada-com-halteres', 'COMPOSTO', 'INICIANTE', 45),
  ('cadeira-extensora', 'ISOLADO', 'INICIANTE', 46),
  ('stiff-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 47),
  ('levantamento-terra-convencional', 'COMPOSTO', 'AVANÇADO', 48),
  ('levantamento-terra-com-barra-hexagonal', 'COMPOSTO', 'INTERMEDIÁRIO', 49),
  ('stiff-com-halteres', 'COMPOSTO', 'INICIANTE', 50),
  ('mesa-flexora', 'ISOLADO', 'INICIANTE', 51),
  ('cadeira-flexora', 'ISOLADO', 'INICIANTE', 52),
  ('elevacao-pelvica-hip-thrust-com-barra', 'COMPOSTO', 'INTERMEDIÁRIO', 53),
  ('ponte-de-gluteos-peso-do-corpo', 'COMPOSTO', 'INICIANTE', 54),
  ('agachamento-sumo-com-halter', 'COMPOSTO', 'INICIANTE', 55),
  ('gluteo-na-polia-coice', 'ISOLADO', 'INICIANTE', 56),
  ('cadeira-abdutora', 'ISOLADO', 'INICIANTE', 57),
  ('extensao-de-quadril-na-maquina', 'ISOLADO', 'INICIANTE', 58),
  ('panturrilha-em-pe-na-maquina', 'ISOLADO', 'INICIANTE', 59),
  ('panturrilha-sentado', 'ISOLADO', 'INICIANTE', 60),
  ('panturrilha-no-leg-press', 'ISOLADO', 'INICIANTE', 61),
  ('abdominal-na-polia-ajoelhado', 'ISOLADO', 'INTERMEDIÁRIO', 62),
  ('elevacao-de-pernas-na-barra-fixa', 'ISOLADO', 'INTERMEDIÁRIO', 63),
  ('roda-abdominal', 'ISOLADO', 'AVANÇADO', 64),
  ('abdominal-crunch-solo', 'ISOLADO', 'INICIANTE', 65),
  ('prancha', 'ISOLADO', 'INICIANTE', 66),
  ('elevacao-de-pernas-deitado', 'ISOLADO', 'INICIANTE', 67),
  ('extensao-lombar-banco-45', 'ISOLADO', 'INICIANTE', 68),
  ('superman-extensao-no-solo', 'ISOLADO', 'INICIANTE', 69),
  ('rosca-de-punho', 'ISOLADO', 'INICIANTE', 70),
  ('rosca-inversa', 'ISOLADO', 'INICIANTE', 71)
) v("slug", "type", "min_level", "catalog_order")
WHERE e."slug" = v."slug";

-- Catálogo (sem dono) tem as 3 preenchidas; exercício próprio tem as 3 NULL.
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_catalog_rules_check" CHECK (
  ("owner_user_id" IS NULL AND "type" IS NOT NULL AND "min_level" IS NOT NULL AND "catalog_order" IS NOT NULL)
  OR ("owner_user_id" IS NOT NULL AND "type" IS NULL AND "min_level" IS NULL AND "catalog_order" IS NULL)
);

-- Aba Sessoes: slots do plano default. position = ordem do slot dentro do dia (a ordem importa pro algoritmo).
CREATE TABLE "workout_template_slots" (
    "days_per_week" SMALLINT NOT NULL,
    "day" SMALLINT NOT NULL,
    "session_name" VARCHAR(50) NOT NULL,
    "position" SMALLINT NOT NULL,
    "muscle_group" VARCHAR(100) NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "min_level" VARCHAR(20) NOT NULL,
    "sex" VARCHAR(5) NOT NULL,

    CONSTRAINT "workout_template_slots_pkey" PRIMARY KEY ("days_per_week", "day", "position"),
    CONSTRAINT "workout_template_slots_day_check" CHECK ("day" BETWEEN 1 AND "days_per_week"),
    CONSTRAINT "workout_template_slots_position_check" CHECK ("position" >= 1),
    CONSTRAINT "workout_template_slots_muscle_group_check" CHECK ("muscle_group" IN ('Peito', 'Costas', 'Ombros', 'Bíceps', 'Tríceps', 'Quadríceps', 'Posterior de coxa', 'Glúteos', 'Panturrilha', 'Abdômen', 'Lombar', 'Antebraço')),
    CONSTRAINT "workout_template_slots_type_check" CHECK ("type" IN ('COMPOSTO', 'ISOLADO')),
    CONSTRAINT "workout_template_slots_min_level_check" CHECK ("min_level" IN ('INICIANTE', 'INTERMEDIÁRIO', 'AVANÇADO')),
    CONSTRAINT "workout_template_slots_sex_check" CHECK ("sex" IN ('TODOS', 'M', 'F', 'N'))
);

-- RLS: mesmo padrão de 20260925180000_lock_down_public_schema (tabela nova = ENABLE + policy do torv_api;
-- anon/authenticated ficam sem grant pelos default privileges daquela migration).
ALTER TABLE "workout_template_slots" ENABLE ROW LEVEL SECURITY;
CREATE POLICY torv_api_full_access ON "workout_template_slots" TO torv_api USING (true) WITH CHECK (true);

INSERT INTO "workout_template_slots" ("days_per_week", "day", "session_name", "position", "muscle_group", "type", "min_level", "sex") VALUES
  (3, 1, 'Corpo todo A', 1, 'Quadríceps', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 1, 'Corpo todo A', 2, 'Peito', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 1, 'Corpo todo A', 3, 'Costas', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 1, 'Corpo todo A', 4, 'Ombros', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 1, 'Corpo todo A', 5, 'Peito', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 1, 'Corpo todo A', 6, 'Ombros', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 1, 'Corpo todo A', 7, 'Peito', 'ISOLADO', 'INICIANTE', 'M'),
  (3, 1, 'Corpo todo A', 8, 'Ombros', 'ISOLADO', 'INICIANTE', 'F'),
  (3, 1, 'Corpo todo A', 9, 'Bíceps', 'ISOLADO', 'INICIANTE', 'N'),
  (3, 1, 'Corpo todo A', 10, 'Abdômen', 'ISOLADO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 1, 'Posterior de coxa', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 2, 'Glúteos', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 3, 'Costas', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 4, 'Costas', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 2, 'Corpo todo B', 5, 'Peito', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 6, 'Quadríceps', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 2, 'Corpo todo B', 7, 'Tríceps', 'ISOLADO', 'INICIANTE', 'TODOS'),
  (3, 2, 'Corpo todo B', 8, 'Panturrilha', 'ISOLADO', 'INICIANTE', 'TODOS'),
  (3, 3, 'Corpo todo C', 1, 'Quadríceps', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 3, 'Corpo todo C', 2, 'Ombros', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 3, 'Corpo todo C', 3, 'Posterior de coxa', 'ISOLADO', 'INICIANTE', 'TODOS'),
  (3, 3, 'Corpo todo C', 4, 'Glúteos', 'COMPOSTO', 'INICIANTE', 'TODOS'),
  (3, 3, 'Corpo todo C', 5, 'Posterior de coxa', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 3, 'Corpo todo C', 6, 'Glúteos', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (3, 3, 'Corpo todo C', 7, 'Panturrilha', 'ISOLADO', 'INICIANTE', 'M'),
  (3, 3, 'Corpo todo C', 8, 'Glúteos', 'ISOLADO', 'INICIANTE', 'F'),
  (3, 3, 'Corpo todo C', 9, 'Abdômen', 'ISOLADO', 'INICIANTE', 'N'),
  (3, 3, 'Corpo todo C', 10, 'Bíceps', 'ISOLADO', 'INICIANTE', 'TODOS'),
  (4, 1, 'Superior A', 1, 'Peito', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 2, 'Costas', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 3, 'Ombros', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 4, 'Peito', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 5, 'Costas', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 6, 'Bíceps', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 1, 'Superior A', 7, 'Tríceps', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 1, 'Quadríceps', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 2, 'Posterior de coxa', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 3, 'Glúteos', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 4, 'Quadríceps', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 5, 'Panturrilha', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 2, 'Inferior A', 6, 'Abdômen', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 1, 'Costas', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 2, 'Peito', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 3, 'Ombros', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 4, 'Ombros', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 5, 'Bíceps', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 3, 'Superior B', 6, 'Peito', 'ISOLADO', 'INTERMEDIÁRIO', 'M'),
  (4, 3, 'Superior B', 7, 'Ombros', 'ISOLADO', 'INTERMEDIÁRIO', 'F'),
  (4, 3, 'Superior B', 8, 'Tríceps', 'ISOLADO', 'INTERMEDIÁRIO', 'N'),
  (4, 4, 'Inferior B', 1, 'Quadríceps', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 2, 'Posterior de coxa', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 3, 'Glúteos', 'COMPOSTO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 4, 'Posterior de coxa', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 5, 'Glúteos', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 6, 'Panturrilha', 'ISOLADO', 'INTERMEDIÁRIO', 'TODOS'),
  (4, 4, 'Inferior B', 7, 'Panturrilha', 'ISOLADO', 'INTERMEDIÁRIO', 'M'),
  (4, 4, 'Inferior B', 8, 'Glúteos', 'ISOLADO', 'INTERMEDIÁRIO', 'F'),
  (4, 4, 'Inferior B', 9, 'Abdômen', 'ISOLADO', 'INTERMEDIÁRIO', 'N'),
  (5, 1, 'Empurrar (Push)', 1, 'Peito', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 2, 'Peito', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 3, 'Ombros', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 4, 'Peito', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 5, 'Ombros', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 6, 'Tríceps', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 1, 'Empurrar (Push)', 7, 'Tríceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 1, 'Costas', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 2, 'Costas', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 3, 'Costas', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 4, 'Costas', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 5, 'Ombros', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 6, 'Bíceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 7, 'Bíceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 2, 'Puxar (Pull)', 8, 'Antebraço', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 1, 'Quadríceps', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 2, 'Quadríceps', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 3, 'Quadríceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 4, 'Posterior de coxa', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 5, 'Posterior de coxa', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 6, 'Glúteos', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 7, 'Glúteos', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 8, 'Panturrilha', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 3, 'Pernas', 9, 'Panturrilha', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 1, 'Peito', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 2, 'Costas', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 3, 'Ombros', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 4, 'Bíceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 5, 'Tríceps', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 6, 'Abdômen', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 4, 'Superior', 7, 'Peito', 'ISOLADO', 'AVANÇADO', 'M'),
  (5, 4, 'Superior', 8, 'Ombros', 'ISOLADO', 'AVANÇADO', 'F'),
  (5, 4, 'Superior', 9, 'Antebraço', 'ISOLADO', 'AVANÇADO', 'N'),
  (5, 5, 'Inferior + Core', 1, 'Quadríceps', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 2, 'Posterior de coxa', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 3, 'Glúteos', 'COMPOSTO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 4, 'Posterior de coxa', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 5, 'Glúteos', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 6, 'Abdômen', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 7, 'Lombar', 'ISOLADO', 'AVANÇADO', 'TODOS'),
  (5, 5, 'Inferior + Core', 8, 'Panturrilha', 'ISOLADO', 'AVANÇADO', 'M'),
  (5, 5, 'Inferior + Core', 9, 'Glúteos', 'ISOLADO', 'AVANÇADO', 'F'),
  (5, 5, 'Inferior + Core', 10, 'Abdômen', 'ISOLADO', 'AVANÇADO', 'N');
